# Generated by Django 6.0.2 on 2026-02-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='c_password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
