# Generated by Django 6.0.2 on 2026-02-24 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_manager_c_password_manager_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
