# Generated by Django 6.0.2 on 2026-03-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('Number_of_plate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
